import type { Metadata } from "next";
import "../../../src/styles//scss/globals.scss";
import ThemeRegistry from "@/theme/ThemeRegistry";

export const metadata: Metadata = {
  title: "Admin Panel By Amir Honarmand",
  description: "Generated by me",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="overflow-x-hidden">
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
