import type { Metadata } from "next";
import "../../../src/styles/scss/globals.scss";
import ThemeRegistry from "@/theme/ThemeRegistry";
import BasicLayout from "@/layouts/BasicLayout";
import CustomProvider from "@/redux/provider";

export const metadata: Metadata = {
  title: "Admin Panel By Amir Honarmand",
  description: "Generated by me",
  icons: [
    // {
    //   rel: 'apple-touch-icon',
    //   url: '/apple-touch-icon.png',
    // },
    // {
    //   rel: 'icon',
    //   type: 'image/png',
    //   sizes: '32x32',
    //   url: '/favicon-32x32.png',
    // },
    // {
    //   rel: 'icon',
    //   type: 'image/png',
    //   sizes: '16x16',
    //   url: '/favicon-16x16.png',
    // },
    {
      rel: "icon",
      url: "/favicon.ico",
    },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="overflow-x-hidden">
        <CustomProvider>
          <ThemeRegistry>
            <BasicLayout>{children}</BasicLayout>
          </ThemeRegistry>
        </CustomProvider>
      </body>
    </html>
  );
}
