import type { Metadata } from "next";
import "../../../styles/scss/globals.scss";
import ThemeRegistry from "@/theme/ThemeRegistry";
import FavIcon from '@/app/favicon.ico';

export const metadata: Metadata = {
  title: "Admin Panel By Amir Honarmand | Login",
  description: "Generated by me",
  icons: [
    // {
    //   rel: 'apple-touch-icon',
    //   url: '/apple-touch-icon.png',
    // },
    // {
    //   rel: 'icon',
    //   type: 'image/png',
    //   sizes: '32x32',
    //   url: '/favicon-32x32.png',
    // },
    // {
    //   rel: 'icon',
    //   type: 'image/png',
    //   sizes: '16x16',
    //   url: '/favicon-16x16.png',
    // },
    {
      rel: "icon",
      url: FavIcon.src,
    },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
