import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Roboto } from "next/font/google";
import ThemeRegistry from "@/theme/ThemeRegistry";

// const vazirFont = localFont({
//   src: "../assets/fonts/Vazir.woff2",
//   display: "swap",
//   variable: "--font-vazir",
// });

// const robotoFont = Roboto({
//   subsets: ["latin"],
//   display: "swap",
//   weight: ["100", "300", "400", "500", "700", "900"],
// });

export const metadata: Metadata = {
  title: "Admin Panel By Amir Honarmand",
  description: "Generated by me",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      {/* <body className={vazirFont.className}>{children}</body> */}
      <body>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
